# Generated by Django 5.0.3 on 2024-06-16 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0002_alter_transaction_sacco_ref_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('savings_multiplier', models.DecimalField(decimal_places=2, default=3.0, max_digits=5)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('max_repayment_period', models.IntegerField(default=36)),
                ('min_membership_age', models.DurationField(default='00:10:00')),
                ('processing_fee_less_100k', models.DecimalField(decimal_places=2, default=1500.0, max_digits=10)),
                ('processing_fee_100k_to_1M', models.DecimalField(decimal_places=2, default=2000.0, max_digits=10)),
                ('processing_fee_above_1M', models.DecimalField(decimal_places=2, default=5000.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='IssuedLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_ref_id', models.CharField(max_length=20, unique=True)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('repayment_period', models.IntegerField()),
                ('installment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loan_purpose', models.CharField(max_length=255)),
                ('grace_period', models.IntegerField(default=0)),
                ('repayments_start_date', models.DateField()),
                ('installment_every', models.CharField(default='1 month', max_length=20)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('loan_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.loanproduct')),
            ],
        ),
        migrations.CreateModel(
            name='Collateral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collateral_type', models.CharField(choices=[('log_book', 'Log Book'), ('land_title_deed', 'Land Title Deed'), ('official_letter', 'Official Letter'), ('guarantors', 'Guarantors')], max_length=20)),
                ('document_ref_no', models.CharField(blank=True, max_length=100, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('guarantee_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('guarantor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guaranteed_loans', to='members.member')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.issuedloan')),
            ],
        ),
    ]
