# Generated by Django 5.0.3 on 2024-06-19 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_remove_collateral_guarantee_amount_and_more'),
        ('members', '0004_transaction_tr_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guarantor',
            name='guarantor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guaranteed_loans', to='members.member'),
        ),
    ]
