# Generated by Django 5.0.3 on 2024-06-20 00:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_alter_guarantor_guarantor'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuedloan',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
