# Generated by Django 5.0.3 on 2024-06-22 05:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_collateral_loan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuedloan',
            name='loan_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='issuedloan',
            name='loan_status',
            field=models.CharField(choices=[('active', 'Active'), ('settled', 'Settled'), ('overdue', 'Overdue')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='issuedloan',
            name='updated_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
