# Generated by Django 5.0.3 on 2024-06-29 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0007_remove_issuedloan_member_issuedloan_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedloan',
            name='object_id',
            field=models.CharField(max_length=15),
        ),
    ]
