# Generated by Django 5.0.3 on 2024-07-18 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0008_alter_issuedloan_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedloan',
            name='loan_status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('active', 'Active'), ('settled', 'Settled'), ('overdue', 'Overdue')], default='pending', max_length=10),
        ),
    ]
