# Generated by Django 5.0.3 on 2024-07-18 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0009_alter_issuedloan_loan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='collateral',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='collateral_documents/'),
        ),
        migrations.AddField(
            model_name='issuedloan',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='issuedloan',
            name='loan_status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejcted'), ('active', 'Active'), ('settled', 'Settled'), ('overdue', 'Overdue')], default='pending', max_length=10),
        ),
    ]
