# Generated by Django 5.0.3 on 2024-06-26 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_name', models.CharField(max_length=255)),
                ('reg_cert_number', models.CharField(max_length=50)),
                ('entity_type', models.CharField(choices=[('public_company', 'Public Company'), ('private_company', 'Private Company'), ('chama', 'Chama'), ('church', 'Church')], max_length=50)),
                ('annual_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('head_office_address', models.TextField()),
                ('office_phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='EntityAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_fee', models.DecimalField(decimal_places=2, default=5000.0, max_digits=10)),
                ('share_capital', models.DecimalField(decimal_places=2, default=10000.0, max_digits=10)),
                ('loan', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.entity')),
            ],
        ),
        migrations.CreateModel(
            name='EntityAccountsLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('transaction_type', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.entity')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EntityOfficial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(choices=[('treasurer', 'Treasurer'), ('chairman', 'Chairman'), ('secretary', 'Secretary')], max_length=50)),
                ('national_id', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('signature', models.ImageField(upload_to='signatures/')),
                ('photo', models.ImageField(upload_to='photos/')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.entity')),
            ],
        ),
    ]
