# Generated by Django 5.0.3 on 2024-06-27 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityaccount',
            name='savings',
            field=models.DecimalField(decimal_places=2, default=5000.0, max_digits=10),
        ),
    ]
