# Generated by Django 5.0.3 on 2024-06-27 06:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_entityaccount_savings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entityaccountsledger',
            old_name='amount',
            new_name='tr_amount',
        ),
        migrations.RemoveField(
            model_name='entityaccountsledger',
            name='description',
        ),
        migrations.RemoveField(
            model_name='entityaccountsledger',
            name='transaction_date',
        ),
        migrations.RemoveField(
            model_name='entityaccountsledger',
            name='transaction_type',
        ),
        migrations.AddField(
            model_name='entityaccountsledger',
            name='external_ref_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='entityaccountsledger',
            name='sacco_ref_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='entityaccountsledger',
            name='tr_account',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entityaccountsledger',
            name='tr_destn',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entityaccountsledger',
            name='tr_mode_id',
            field=models.IntegerField(choices=[(1, 'Mpesa'), (2, 'Cash'), (3, 'Bank Transfer')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entityaccountsledger',
            name='tr_origin',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entityaccountsledger',
            name='tr_type',
            field=models.CharField(choices=[(1, 'Debit'), (2, 'Credit')], default=1, max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entity',
            name='head_office_address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='entityaccountsledger',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
