# Generated by Django 5.0.3 on 2024-06-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_rename_amount_entityaccountsledger_tr_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityaccountsledger',
            name='tr_account',
            field=models.CharField(max_length=50),
        ),
    ]
