# Generated by Django 5.0.3 on 2024-06-28 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_alter_entityaccountsledger_tr_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='id',
            field=models.CharField(editable=False, max_length=15, primary_key=True, serialize=False),
        ),
    ]
