# Generated by Django 5.0.3 on 2024-07-01 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_rename_updated_by_entity_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityaccount',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='groups.entity', unique='True'),
        ),
    ]
