# Generated by Django 5.0.3 on 2024-07-01 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_alter_entityaccount_entity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityaccount',
            name='entity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='groups.entity'),
        ),
    ]
