# Generated by Django 5.0.3 on 2024-06-15 10:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('member_national_id', models.CharField(max_length=20)),
                ('registration_date', models.DateField(default=django.utils.timezone.now)),
                ('phone_number', models.CharField(max_length=15)),
                ('secondary_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('client_type', models.CharField(choices=[('individual', 'Individual'), ('group', 'Group'), ('organization', 'Organization')], max_length=20)),
                ('client_photo', models.ImageField(blank=True, null=True, upload_to='client_photos/')),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=10)),
                ('address', models.CharField(max_length=255)),
                ('town', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('employment_status', models.CharField(choices=[('employed', 'Employed'), ('self_employed', 'Self Employed'), ('unemployed', 'Unemployed')], max_length=20)),
                ('employment_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('spouse_name', models.CharField(blank=True, max_length=100, null=True)),
                ('spouse_address', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MemberAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_capital', models.DecimalField(decimal_places=2, max_digits=10)),
                ('savings', models.DecimalField(decimal_places=2, default=1000.0, max_digits=10)),
                ('reg_fee', models.DecimalField(decimal_places=2, default=1500.0, max_digits=10)),
                ('loan', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
            ],
        ),
        migrations.CreateModel(
            name='NextOfKin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('relationship', models.CharField(max_length=100)),
                ('kin_national_id', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sacco_ref_code', models.CharField(default='8a01aef2', max_length=8, unique=True)),
                ('tr_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tr_account', models.CharField(max_length=20)),
                ('account_id', models.IntegerField()),
                ('tr_mode_id', models.IntegerField(choices=[(1, 'Mpesa'), (2, 'Cash'), (3, 'Bank Transfer')])),
                ('tr_destn', models.CharField(max_length=100)),
                ('external_ref_code', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(default='system', max_length=100)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
            ],
        ),
    ]
