# Generated by Django 5.0.3 on 2024-06-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='sacco_ref_code',
            field=models.CharField(default='8d814a05', max_length=8, unique=True),
        ),
    ]
