# Generated by Django 5.0.3 on 2024-06-18 10:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_transaction_sacco_ref_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='tr_type',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='member_national_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='external_ref_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sacco_ref_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='MemberAccountsLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sacco_ref_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('tr_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tr_type', models.CharField(max_length=100)),
                ('tr_account', models.CharField(max_length=20)),
                ('account_id', models.IntegerField()),
                ('tr_mode_id', models.IntegerField(choices=[(1, 'Mpesa'), (2, 'Cash'), (3, 'Bank Transfer')])),
                ('tr_origin', models.CharField(max_length=100)),
                ('tr_destn', models.CharField(max_length=100)),
                ('external_ref_code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('updated_by', models.CharField(default='system', max_length=100)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
            ],
        ),
    ]
