# Generated by Django 5.0.3 on 2024-06-19 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_transaction_tr_type_alter_member_member_national_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='tr_origin',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
