# Generated by Django 5.0.3 on 2024-06-24 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_transaction_tr_origin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MemberAccountsLedger',
        ),
    ]
