# Generated by Django 5.0.3 on 2024-07-18 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_memberaccountsledger'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memberaccount',
            old_name='loan',
            new_name='mobile_wallet',
        ),
    ]
