# Generated by Django 5.0.3 on 2024-07-12 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_saccoaccount_account_balance_saccoaccount_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaReconciliationLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_no', models.CharField(max_length=100, unique=True, verbose_name='Receipt Number')),
                ('completion_date', models.DateTimeField(verbose_name='Completion Date')),
                ('paid_in', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Paid In Amount')),
                ('account_no', models.CharField(max_length=50, verbose_name='Account Reference')),
                ('priority', models.CharField(choices=[('savings_first', 'Savings First'), ('loan_repayment_first', 'Loan Repayment First')], max_length=20, verbose_name='Priority')),
                ('reconciled', models.BooleanField(default=False, verbose_name='Reconciled')),
                ('reconciled_at', models.DateTimeField(blank=True, null=True, verbose_name='Reconciled At')),
            ],
            options={
                'verbose_name': 'M-Pesa Reconciliation Entry',
                'verbose_name_plural': 'M-Pesa Reconciliation Entries',
            },
        ),
    ]
