# Generated by Django 5.0.3 on 2024-07-12 06:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_mpesareconciliationledger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesareconciliationledger',
            name='reconciled_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
