# Generated by Django 5.0.3 on 2024-10-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_alter_mpesareconciliationledger_completion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saccoaccount',
            name='account_type',
            field=models.CharField(choices=[('income', 'Income Account'), ('expenditure', 'Expenditure Account'), ('fixed_asset', 'Fixed Asset Account'), ('current_asset', 'Current Asset Account'), ('current_liability', 'Current Liability Account'), ('long_term_liability', 'Long-Term Liability Account')], max_length=50),
        ),
    ]
